// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/duku-hero/BoldOrange.tsx": () => import("../components/mockups/duku-hero/BoldOrange.tsx"),
  "./components/mockups/duku-hero/DarkOrangeAccent.tsx": () => import("../components/mockups/duku-hero/DarkOrangeAccent.tsx")
};
